//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class CharacterConfig :  Bright.Config.BeanBase 
{
    public CharacterConfig(JSONNode _json) 
    {
        { if(!_json["id"].IsString) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        { if(!_json["image"].IsString) { throw new SerializationException(); }  Image = _json["image"]; }
        { if(!_json["water_need"].IsNumber) { throw new SerializationException(); }  WaterNeed = _json["water_need"]; }
        { if(!_json["fertile_need"].IsNumber) { throw new SerializationException(); }  FertileNeed = _json["fertile_need"]; }
        { if(!_json["care_need"].IsNumber) { throw new SerializationException(); }  CareNeed = _json["care_need"]; }
        { if(!_json["harvest"].IsNumber) { throw new SerializationException(); }  Harvest = _json["harvest"]; }
        { if(!_json["price"].IsNumber) { throw new SerializationException(); }  Price = _json["price"]; }
        PostInit();
    }

    public CharacterConfig(string id, string name, string image, int water_need, int fertile_need, int care_need, int harvest, int price ) 
    {
        this.Id = id;
        this.Name = name;
        this.Image = image;
        this.WaterNeed = water_need;
        this.FertileNeed = fertile_need;
        this.CareNeed = care_need;
        this.Harvest = harvest;
        this.Price = price;
        PostInit();
    }

    public static CharacterConfig DeserializeCharacterConfig(JSONNode _json)
    {
        return new CharacterConfig(_json);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    public string Image { get; private set; }
    public int WaterNeed { get; private set; }
    public int FertileNeed { get; private set; }
    public int CareNeed { get; private set; }
    public int Harvest { get; private set; }
    public int Price { get; private set; }

    public const int __ID__ = 676994987;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Image:" + Image + ","
        + "WaterNeed:" + WaterNeed + ","
        + "FertileNeed:" + FertileNeed + ","
        + "CareNeed:" + CareNeed + ","
        + "Harvest:" + Harvest + ","
        + "Price:" + Price + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
