//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class EffectConfig :  Bright.Config.BeanBase 
{
    public EffectConfig(JSONNode _json) 
    {
        { if(!_json["id"].IsString) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["life_add"].IsNumber) { throw new SerializationException(); }  LifeAdd = _json["life_add"]; }
        { if(!_json["life_minus"].IsNumber) { throw new SerializationException(); }  LifeMinus = _json["life_minus"]; }
        { if(!_json["cost_add"].IsNumber) { throw new SerializationException(); }  CostAdd = _json["cost_add"]; }
        { if(!_json["cost_minus"].IsNumber) { throw new SerializationException(); }  CostMinus = _json["cost_minus"]; }
        { if(!_json["event_add"].IsNumber) { throw new SerializationException(); }  EventAdd = _json["event_add"]; }
        { if(!_json["event_minus"].IsNumber) { throw new SerializationException(); }  EventMinus = _json["event_minus"]; }
        { if(!_json["branch_add"].IsNumber) { throw new SerializationException(); }  BranchAdd = _json["branch_add"]; }
        { if(!_json["branch_minus"].IsNumber) { throw new SerializationException(); }  BranchMinus = _json["branch_minus"]; }
        PostInit();
    }

    public EffectConfig(string id, int life_add, int life_minus, int cost_add, int cost_minus, int event_add, int event_minus, int branch_add, int branch_minus ) 
    {
        this.Id = id;
        this.LifeAdd = life_add;
        this.LifeMinus = life_minus;
        this.CostAdd = cost_add;
        this.CostMinus = cost_minus;
        this.EventAdd = event_add;
        this.EventMinus = event_minus;
        this.BranchAdd = branch_add;
        this.BranchMinus = branch_minus;
        PostInit();
    }

    public static EffectConfig DeserializeEffectConfig(JSONNode _json)
    {
        return new EffectConfig(_json);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 增加生命值
    /// </summary>
    public int LifeAdd { get; private set; }
    /// <summary>
    /// 减少生命值
    /// </summary>
    public int LifeMinus { get; private set; }
    /// <summary>
    /// 增加衰减值
    /// </summary>
    public int CostAdd { get; private set; }
    /// <summary>
    /// 减少衰减值
    /// </summary>
    public int CostMinus { get; private set; }
    /// <summary>
    /// 增加相遇可能性
    /// </summary>
    public int EventAdd { get; private set; }
    /// <summary>
    /// 减少相遇可能性
    /// </summary>
    public int EventMinus { get; private set; }
    /// <summary>
    /// 增加分支可能性
    /// </summary>
    public int BranchAdd { get; private set; }
    /// <summary>
    /// 减少分支可能性
    /// </summary>
    public int BranchMinus { get; private set; }

    public const int __ID__ = -682668973;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "LifeAdd:" + LifeAdd + ","
        + "LifeMinus:" + LifeMinus + ","
        + "CostAdd:" + CostAdd + ","
        + "CostMinus:" + CostMinus + ","
        + "EventAdd:" + EventAdd + ","
        + "EventMinus:" + EventMinus + ","
        + "BranchAdd:" + BranchAdd + ","
        + "BranchMinus:" + BranchMinus + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
