//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class EffectConfig :  Bright.Config.BeanBase 
{
    public EffectConfig(JSONNode _json) 
    {
        { if(!_json["id"].IsString) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["life_add"].IsNumber) { throw new SerializationException(); }  LifeAdd = _json["life_add"]; }
        { if(!_json["cost_add"].IsNumber) { throw new SerializationException(); }  CostAdd = _json["cost_add"]; }
        { if(!_json["event_add"].IsNumber) { throw new SerializationException(); }  EventAdd = _json["event_add"]; }
        { if(!_json["branch_add"].IsNumber) { throw new SerializationException(); }  BranchAdd = _json["branch_add"]; }
        PostInit();
    }

    public EffectConfig(string id, float life_add, float cost_add, float event_add, float branch_add ) 
    {
        this.Id = id;
        this.LifeAdd = life_add;
        this.CostAdd = cost_add;
        this.EventAdd = event_add;
        this.BranchAdd = branch_add;
        PostInit();
    }

    public static EffectConfig DeserializeEffectConfig(JSONNode _json)
    {
        return new EffectConfig(_json);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public string Id { get; private set; }
    /// <summary>
    /// 增加生命值
    /// </summary>
    public float LifeAdd { get; private set; }
    /// <summary>
    /// 增加衰减值
    /// </summary>
    public float CostAdd { get; private set; }
    /// <summary>
    /// 增加相遇可能性
    /// </summary>
    public float EventAdd { get; private set; }
    /// <summary>
    /// 增加分支可能性
    /// </summary>
    public float BranchAdd { get; private set; }

    public const int __ID__ = -682668973;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "LifeAdd:" + LifeAdd + ","
        + "CostAdd:" + CostAdd + ","
        + "EventAdd:" + EventAdd + ","
        + "BranchAdd:" + BranchAdd + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
