//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;


namespace cfg
{ 
   
public sealed partial class Tables
{
    public TbBaseConfig TbBaseConfig {get; }
    public TbCharacter TbCharacter {get; }
    public TbEffect TbEffect {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbBaseConfig = new TbBaseConfig(loader("tbbaseconfig")); 
        tables.Add("TbBaseConfig", TbBaseConfig);
        TbCharacter = new TbCharacter(loader("tbcharacter")); 
        tables.Add("TbCharacter", TbCharacter);
        TbEffect = new TbEffect(loader("tbeffect")); 
        tables.Add("TbEffect", TbEffect);
        PostInit();

        TbBaseConfig.Resolve(tables); 
        TbCharacter.Resolve(tables); 
        TbEffect.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbBaseConfig.TranslateText(translator); 
        TbCharacter.TranslateText(translator); 
        TbEffect.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}